"""
Council Manager — EvaluationContext + CouncilMember + CouncilManager

Each council member receives the same structured context (tiered by model capacity)
and independently scores, ranks, and critiques all planner plans.
"""

import json
import logging
import time
import requests
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# Evaluation Context
# ─────────────────────────────────────────────────────────────────────────────

EVALUATOR_SYSTEM_PROMPT = """You are an expert evaluator in a MAPE-K autonomic computing system for Pegasus WMS workflows.

Your role is to evaluate repair plans generated by AI planning models against the original workflow failure analysis.

You will receive:
1. ANALYZER RESULT — the diagnosed problems, root causes, and confidence
2. PLANS TO EVALUATE — repair plans from different AI models
3. EVALUATION METRICS — criteria with weights to score each plan

Your task:
1. Score each plan on every metric (0.0 = worst, 1.0 = best)
2. Rank plans from best to worst
3. Flag contradictions: cases where a plan's approach conflicts with the analyzer's identified root cause
4. State your confidence in your own evaluation (0.0–1.0)
5. Write a brief reasoning summary

CRITICAL RULES:
- Score independently and honestly — do not favour any model
- A contradiction is when a plan fixes the wrong thing (e.g., plan adds a replica entry but root cause is a syntax error)
- Safety score must be 0.0 for any plan containing: rm -rf, dd, chmod 777, or irreversible destructive commands
- Output ONLY valid JSON — no markdown, no extra text

Required output structure:
{
  "scores": {
    "<plan_label>": {
      "<metric_name>": <0.0–1.0>,
      ...
    }
  },
  "ranking": ["<best_label>", "<second_label>", ...],
  "contradictions": [
    {"plan": "<label>", "issue": "<description of contradiction>"}
  ],
  "vetoes": [
    {"plan": "<label>", "reason": "<why this plan must be blocked>"}
  ],
  "reasoning": "<brief explanation of your evaluation decisions>",
  "confidence": <0.0–1.0>
}"""


class EvaluationContext:
    """
    Builds tiered prompts from the full evaluation input.
    Prompts are built once and cached — all council members share the same objects.
    """

    def __init__(
        self,
        workflow_id: str,
        analyzer_result: Dict[str, Any],
        plans: Dict[str, Any],
        metrics: List[Dict[str, Any]],
        catalogs: Dict[str, Any] = None,
        workflow_files: Dict[str, Any] = None,
        parent_error_analysis: Dict[str, Any] = None
    ):
        self.workflow_id = workflow_id
        self.analyzer_result = analyzer_result
        self.plans = plans
        self.metrics = metrics
        self.catalogs = catalogs or {}
        self.workflow_files = workflow_files or {}
        self.parent_error_analysis = parent_error_analysis or {}
        self._prompts: Dict[int, str] = {}

    def build_all_tiers(self):
        """Build and cache all tier prompts — called once before council runs"""
        self._prompts[1] = self._build_tier1()
        self._prompts[2] = self._build_tier2()
        self._prompts[3] = self._build_tier3()
        logger.info(
            f"Context tiers built — "
            f"T1:{len(self._prompts[1])} T2:{len(self._prompts[2])} T3:{len(self._prompts[3])} chars"
        )

    def get_prompt(self, tier: int) -> str:
        if not self._prompts:
            self.build_all_tiers()
        return self._prompts.get(tier, self._prompts[2])

    def _metrics_section(self, full: bool = True) -> str:
        lines = []
        for m in self.metrics:
            if full:
                lines.append(f"  - {m['name']} (weight={m['weight']}): {m['description']}")
            else:
                lines.append(f"  - {m['name']} (weight={m['weight']})")
        return "\n".join(lines)

    def _plans_section_full(self) -> str:
        return json.dumps(self.plans, indent=2)

    def _plans_section_compact(self) -> str:
        compact = {}
        for label, plan in self.plans.items():
            compact[label] = {
                "repair_steps": plan.get("repair_steps", []),
                "risk_level": plan.get("risk_level"),
                "confidence": plan.get("confidence")
            }
        return json.dumps(compact, indent=2)

    def _plans_section_essential(self) -> str:
        lines = []
        for label, plan in self.plans.items():
            steps = plan.get("repair_steps", [])
            step_list = "; ".join(
                s.get("command", s.get("action", str(s))) for s in steps[:5]
            )
            lines.append(f"{label}: {step_list}")
        return "\n".join(lines)

    def _analyzer_section_full(self) -> str:
        parts = [json.dumps(self.analyzer_result, indent=2)]
        if self.parent_error_analysis:
            parts.append("PARENT ERROR ANALYSIS:\n" + json.dumps(self.parent_error_analysis, indent=2))
        if self.catalogs:
            parts.append("CATALOGS:\n" + json.dumps(self.catalogs, indent=2))
        return "\n\n".join(parts)

    def _analyzer_section_compact(self) -> str:
        problems = self.analyzer_result.get("problems_and_solutions", [])
        confidence = self.analyzer_result.get("confidence", "unknown")
        return json.dumps({
            "problems_and_solutions": problems,
            "confidence": confidence,
            "parent_error": self.parent_error_analysis.get("parent_error") if self.parent_error_analysis else None
        }, indent=2)

    def _analyzer_section_essential(self) -> str:
        problems = self.analyzer_result.get("problems_and_solutions", [])[:3]
        lines = [f"Workflow: {self.workflow_id}", f"Top problems ({len(problems)}):"]
        for p in problems:
            lines.append(f"  - {p.get('problem', '')}")
        return "\n".join(lines)

    def _build_tier1(self) -> str:
        return f"""WORKFLOW EVALUATION REQUEST
Workflow ID: {self.workflow_id}

═══════════════════════════════════════════════════
ANALYZER RESULT (full)
═══════════════════════════════════════════════════
{self._analyzer_section_full()}

═══════════════════════════════════════════════════
PLANS TO EVALUATE (full)
═══════════════════════════════════════════════════
{self._plans_section_full()}

═══════════════════════════════════════════════════
EVALUATION METRICS
═══════════════════════════════════════════════════
{self._metrics_section(full=True)}

Plan labels to score and rank: {list(self.plans.keys())}

Provide your evaluation as JSON only."""

    def _build_tier2(self) -> str:
        return f"""WORKFLOW EVALUATION REQUEST
Workflow ID: {self.workflow_id}

ANALYZER RESULT:
{self._analyzer_section_compact()}

PLANS TO EVALUATE:
{self._plans_section_compact()}

EVALUATION METRICS:
{self._metrics_section(full=True)}

Plan labels to score and rank: {list(self.plans.keys())}

Provide your evaluation as JSON only."""

    def _build_tier3(self) -> str:
        return f"""WORKFLOW EVALUATION REQUEST
Workflow ID: {self.workflow_id}

ANALYZER RESULT:
{self._analyzer_section_essential()}

PLANS (essential):
{self._plans_section_essential()}

METRICS: {self._metrics_section(full=False)}

Plan labels: {list(self.plans.keys())}

Provide your evaluation as JSON only."""


# ─────────────────────────────────────────────────────────────────────────────
# Council Member
# ─────────────────────────────────────────────────────────────────────────────

class CouncilMember:
    """Single LLM-backed evaluator — calls Ollama or OpenAI"""

    def __init__(self, label: str, tier: int, config: Dict[str, Any]):
        self.label = label
        self.tier = tier
        self.provider, self.model = label.split("/", 1)
        self.ollama_url = config.get("ollama_url")
        self.openai_api_key = config.get("openai_api_key", "")
        self.openai_api_base = config.get("openai_api_base", "https://api.openai.com/v1")
        self.connection_timeout = config.get("connection_timeout", 300)

    def evaluate(self, context: EvaluationContext) -> Dict[str, Any]:
        """Run evaluation and return structured result"""
        prompt = context.get_prompt(self.tier)
        start = time.time()

        try:
            if self.provider == "ollama":
                raw = self._call_ollama(prompt)
            elif self.provider == "openai":
                raw = self._call_openai(prompt)
            else:
                raise ValueError(f"Unknown provider: {self.provider}")

            latency_ms = (time.time() - start) * 1000
            parsed = self._parse(raw)
            parsed["_member"] = self.label
            parsed["_tier"] = self.tier
            parsed["_latency_ms"] = round(latency_ms)
            parsed["_raw_response"] = raw
            parsed["_status"] = "success"
            return parsed

        except Exception as e:
            logger.error(f"Council member {self.label} failed: {e}")
            return {
                "_member": self.label,
                "_tier": self.tier,
                "_status": "failed",
                "_error": str(e),
                "scores": {},
                "ranking": [],
                "contradictions": [],
                "vetoes": [],
                "reasoning": "",
                "confidence": 0.0
            }

    def _call_ollama(self, prompt: str) -> str:
        full_prompt = f"{EVALUATOR_SYSTEM_PROMPT}\n\n{prompt}"
        payload = {
            "model": self.model,
            "prompt": full_prompt,
            "stream": True,
            "format": "json",
            "options": {"temperature": 0.1, "top_p": 0.9, "num_predict": 8000}
        }
        response = requests.post(
            self.ollama_url, json=payload,
            timeout=self.connection_timeout, stream=True
        )
        if response.status_code != 200:
            raise RuntimeError(f"Ollama HTTP {response.status_code}: {response.text[:200]}")
        result = ""
        for line in response.iter_lines():
            if line:
                chunk = json.loads(line.decode("utf-8"))
                result += chunk.get("response", "")
        return result

    def _call_openai(self, prompt: str) -> str:
        if not self.openai_api_key:
            raise RuntimeError("OpenAI API key not configured")
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": EVALUATOR_SYSTEM_PROMPT},
                {"role": "user", "content": prompt}
            ],
            "temperature": 0.1,
            "response_format": {"type": "json_object"},
            "max_tokens": 8000
        }
        response = requests.post(
            f"{self.openai_api_base}/chat/completions",
            headers={
                "Authorization": f"Bearer {self.openai_api_key}",
                "Content-Type": "application/json"
            },
            json=payload,
            timeout=self.connection_timeout
        )
        if response.status_code != 200:
            raise RuntimeError(f"OpenAI HTTP {response.status_code}: {response.text[:200]}")
        return response.json()["choices"][0]["message"]["content"]

    def _parse(self, raw: str) -> Dict[str, Any]:
        """Parse LLM JSON output with fallback"""
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            # Try to extract JSON block
            import re
            match = re.search(r'\{.*\}', raw, re.DOTALL)
            if match:
                data = json.loads(match.group())
            else:
                raise ValueError(f"Cannot parse LLM output as JSON: {raw[:200]}")

        return {
            "scores": data.get("scores", {}),
            "ranking": data.get("ranking", []),
            "contradictions": data.get("contradictions", []),
            "vetoes": data.get("vetoes", []),
            "reasoning": data.get("reasoning", ""),
            "confidence": float(data.get("confidence", 0.5))
        }


# ─────────────────────────────────────────────────────────────────────────────
# Council Manager
# ─────────────────────────────────────────────────────────────────────────────

class CouncilManager:
    """Spawns all council members in parallel and collects evaluations"""

    def __init__(self, config: Dict[str, Any]):
        self.members = [
            CouncilMember(m["label"], m.get("tier", 2), config)
            for m in config.get("council_models", [])
        ]
        self.tier_weights = {
            int(k): float(v)
            for k, v in config.get("tier_weights", {"1": 1.0, "2": 0.75, "3": 0.5}).items()
        }

        if not self.members:
            logger.warning("No council models configured — evaluator will have no members")

    def run_council(self, context: EvaluationContext) -> Dict[str, Dict[str, Any]]:
        """Run all members in parallel, return {label: evaluation}"""
        if not self.members:
            return {}

        logger.info(f"Running council with {len(self.members)} member(s)")
        results = {}

        with ThreadPoolExecutor(max_workers=len(self.members)) as executor:
            futures = {
                executor.submit(m.evaluate, context): m.label
                for m in self.members
            }
            for future in as_completed(futures):
                label = futures[future]
                try:
                    result = future.result()
                except Exception as e:
                    logger.error(f"Council member {label} thread error: {e}")
                    result = {
                        "_member": label, "_status": "failed", "_error": str(e),
                        "scores": {}, "ranking": [], "contradictions": [],
                        "vetoes": [], "reasoning": "", "confidence": 0.0
                    }
                results[label] = result
                status = "✓" if result.get("_status") == "success" else "✗"
                logger.info(f"  {status} {label}: confidence={result.get('confidence', 0):.2f}")

        return results
